### ISSUE TITLE
jQuery.fn.load() is deprecated 

### ISSUE THREAD

**Issue by alinclamba** [pixelgrade/category-icon#10]
After installing WordPress 5.5, using [jQuery Migrate Helper](https://wordpress.org/plugins/enable-jquery-migrate-helper/) plugin, I've got this warning:

`wp-content/plugins/category-icon/assets/js/category-icon.js: jQuery.fn.load() is deprecated`

Also, it might help to test the plugin with latest version of WordPress and release an update, with a mention about the compatibility. For now, the plugin isn't tested with the latest 3 major releases of WordPress and it has been updated more than a year ago. 

https://wordpress.org/plugins/category-icon/

**Comment by madalingorbanescu** [comment]
I have created a [new issue](https://github.com/pixelgrade/category-icon/issues/11) where I will address compatibility with WordPress 5.7.
