### ISSUE TITLE
PHP 7.2  E_WARNING

### ISSUE THREAD

**Issue by 262media** [pixelgrade/category-icon#5]
( ! ) Warning: count(): Parameter must be an array or an object that implements Countable in /srv/www/wwwwwww.com/current/web/app/plugins/category-icon/category-icon.php on line 430
--

1 | 7.1520 | 85600528 | shutdown_action_hook( ) | .../load.php:0
2 | 7.1520 | 85600528 | do_action( ) | .../load.php:679
3 | 7.1520 | 85600904 | WP_Hook->do_action( ) | .../plugin.php:453
4 | 7.1520 | 85600904 | WP_Hook->apply_filters( ) | .../class-wp-hook.php:310
5 | 7.1521 | 85602008 | PixTaxonomyIconsPlugin->on_shutdown( ) | .../class-wp-hook.php:286

## Reference:
**An E_WARNING will now be emitted when attempting to count() non-countable types (this includes the sizeof() alias function).**
[http://php.net/manual/en/migration72.incompatible.php#migration72.incompatible.warn-on-non-countable-types](url)

**Comment by raduconst** [comment]
I think that line 430 needs to be changed from:
`$ob_levels = count(ob_get_level());`
to
`$ob_levels = ob_get_level();`
in order to get things fixed.
